package in.coderinfotech.batchschedule;
// Generated Jan 20, 2018 8:05:27 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * BatchDetails generated by hbm2java
 */
public class BatchDetails implements java.io.Serializable {

	private long batchId;
	private String batchName;
	private String trainerName;
	private Date startDate;
	private Date endDate;
	private String duration;
	private String timing;
	private String center;
	private String lab;
	private String capacity;
	private String batchSchedule;
	private Character isCompleted;

	public BatchDetails() {
	}

	public BatchDetails(long batchId) {
		this.batchId = batchId;
	}

	public BatchDetails(long batchId, String batchName, String trainerName, Date startDate, Date endDate,
			String duration, String timing, String center, String lab, String capacity, String batchSchedule,
			Character isCompleted) {
		this.batchId = batchId;
		this.batchName = batchName;
		this.trainerName = trainerName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.duration = duration;
		this.timing = timing;
		this.center = center;
		this.lab = lab;
		this.capacity = capacity;
		this.batchSchedule = batchSchedule;
		this.isCompleted = isCompleted;
	}

	public long getBatchId() {
		return this.batchId;
	}

	public void setBatchId(long batchId) {
		this.batchId = batchId;
	}

	public String getBatchName() {
		return this.batchName;
	}

	public void setBatchName(String batchName) {
		this.batchName = batchName;
	}

	public String getTrainerName() {
		return this.trainerName;
	}

	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getTiming() {
		return this.timing;
	}

	public void setTiming(String timing) {
		this.timing = timing;
	}

	public String getCenter() {
		return this.center;
	}

	public void setCenter(String center) {
		this.center = center;
	}

	public String getLab() {
		return this.lab;
	}

	public void setLab(String lab) {
		this.lab = lab;
	}

	public String getCapacity() {
		return this.capacity;
	}

	public void setCapacity(String capacity) {
		this.capacity = capacity;
	}

	public String getBatchSchedule() {
		return this.batchSchedule;
	}

	public void setBatchSchedule(String batchSchedule) {
		this.batchSchedule = batchSchedule;
	}

	public Character getIsCompleted() {
		return this.isCompleted;
	}

	public void setIsCompleted(Character isCompleted) {
		this.isCompleted = isCompleted;
	}

}
