package hibernate.in.coderinfotech.batchschedule;
// Generated Jan 22, 2018 5:23:28 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchDetails generated by hbm2java
 */
@Entity
@Table(name = "batch_details", catalog = "coderspringmvc")
public class BatchDetails implements java.io.Serializable {

	private long batchId;
	private String batchName;
	private String trainerName;
	private Date startDate;
	private Date endDate;
	private String duration;
	private String timing;
	private String center;
	private String lab;
	private String capacity;
	private String batchSchedule;
	private Character isCompleted;

	public BatchDetails() {
	}

	public BatchDetails(long batchId) {
		this.batchId = batchId;
	}

	public BatchDetails(long batchId, String batchName, String trainerName, Date startDate, Date endDate,
			String duration, String timing, String center, String lab, String capacity, String batchSchedule,
			Character isCompleted) {
		this.batchId = batchId;
		this.batchName = batchName;
		this.trainerName = trainerName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.duration = duration;
		this.timing = timing;
		this.center = center;
		this.lab = lab;
		this.capacity = capacity;
		this.batchSchedule = batchSchedule;
		this.isCompleted = isCompleted;
	}

	@Id

	@Column(name = "BATCH_ID", unique = true, nullable = false)
	public long getBatchId() {
		return this.batchId;
	}

	public void setBatchId(long batchId) {
		this.batchId = batchId;
	}

	@Column(name = "BATCH_NAME", length = 50)
	public String getBatchName() {
		return this.batchName;
	}

	public void setBatchName(String batchName) {
		this.batchName = batchName;
	}

	@Column(name = "TRAINER_NAME", length = 50)
	public String getTrainerName() {
		return this.trainerName;
	}

	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "DURATION", length = 50)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "TIMING", length = 50)
	public String getTiming() {
		return this.timing;
	}

	public void setTiming(String timing) {
		this.timing = timing;
	}

	@Column(name = "CENTER", length = 50)
	public String getCenter() {
		return this.center;
	}

	public void setCenter(String center) {
		this.center = center;
	}

	@Column(name = "LAB", length = 50)
	public String getLab() {
		return this.lab;
	}

	public void setLab(String lab) {
		this.lab = lab;
	}

	@Column(name = "CAPACITY", length = 50)
	public String getCapacity() {
		return this.capacity;
	}

	public void setCapacity(String capacity) {
		this.capacity = capacity;
	}

	@Column(name = "BATCH_SCHEDULE", length = 65535)
	public String getBatchSchedule() {
		return this.batchSchedule;
	}

	public void setBatchSchedule(String batchSchedule) {
		this.batchSchedule = batchSchedule;
	}

	@Column(name = "IS_COMPLETED", length = 1)
	public Character getIsCompleted() {
		return this.isCompleted;
	}

	public void setIsCompleted(Character isCompleted) {
		this.isCompleted = isCompleted;
	}

}
