package in.coderinfotech.batchschedule;
// Generated Jan 20, 2018 8:05:27 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CityMst generated by hbm2java
 */
public class CityMst implements java.io.Serializable {

	private long cityId;
	private StateMst stateMst;
	private String cityCode;
	private String cityName;
	private Set<PersonDetails> personDetailses = new HashSet<PersonDetails>(0);

	public CityMst() {
	}

	public CityMst(long cityId) {
		this.cityId = cityId;
	}

	public CityMst(long cityId, StateMst stateMst, String cityCode, String cityName,
			Set<PersonDetails> personDetailses) {
		this.cityId = cityId;
		this.stateMst = stateMst;
		this.cityCode = cityCode;
		this.cityName = cityName;
		this.personDetailses = personDetailses;
	}

	public long getCityId() {
		return this.cityId;
	}

	public void setCityId(long cityId) {
		this.cityId = cityId;
	}

	public StateMst getStateMst() {
		return this.stateMst;
	}

	public void setStateMst(StateMst stateMst) {
		this.stateMst = stateMst;
	}

	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public Set<PersonDetails> getPersonDetailses() {
		return this.personDetailses;
	}

	public void setPersonDetailses(Set<PersonDetails> personDetailses) {
		this.personDetailses = personDetailses;
	}

}
