package in.coderinfotech.batchschedule;
// Generated Jan 20, 2018 8:05:27 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * EmploymentDetails generated by hbm2java
 */
public class EmploymentDetails implements java.io.Serializable {

	private long employmentDetailsId;
	private String employer;
	private String positionHeld;
	private Date dateOfJoining;
	private Date dateOfLeaving;
	private String payWithScaleOfPay;

	public EmploymentDetails() {
	}

	public EmploymentDetails(long employmentDetailsId) {
		this.employmentDetailsId = employmentDetailsId;
	}

	public EmploymentDetails(long employmentDetailsId, String employer, String positionHeld, Date dateOfJoining,
			Date dateOfLeaving, String payWithScaleOfPay) {
		this.employmentDetailsId = employmentDetailsId;
		this.employer = employer;
		this.positionHeld = positionHeld;
		this.dateOfJoining = dateOfJoining;
		this.dateOfLeaving = dateOfLeaving;
		this.payWithScaleOfPay = payWithScaleOfPay;
	}

	public long getEmploymentDetailsId() {
		return this.employmentDetailsId;
	}

	public void setEmploymentDetailsId(long employmentDetailsId) {
		this.employmentDetailsId = employmentDetailsId;
	}

	public String getEmployer() {
		return this.employer;
	}

	public void setEmployer(String employer) {
		this.employer = employer;
	}

	public String getPositionHeld() {
		return this.positionHeld;
	}

	public void setPositionHeld(String positionHeld) {
		this.positionHeld = positionHeld;
	}

	public Date getDateOfJoining() {
		return this.dateOfJoining;
	}

	public void setDateOfJoining(Date dateOfJoining) {
		this.dateOfJoining = dateOfJoining;
	}

	public Date getDateOfLeaving() {
		return this.dateOfLeaving;
	}

	public void setDateOfLeaving(Date dateOfLeaving) {
		this.dateOfLeaving = dateOfLeaving;
	}

	public String getPayWithScaleOfPay() {
		return this.payWithScaleOfPay;
	}

	public void setPayWithScaleOfPay(String payWithScaleOfPay) {
		this.payWithScaleOfPay = payWithScaleOfPay;
	}

}
