package in.coderinfotech.batchschedule;
// Generated Jan 20, 2018 8:05:27 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PersonDetails generated by hbm2java
 */
public class PersonDetails implements java.io.Serializable {

	private long personDetailsId;
	private AcademicDetails academicDetails;
	private CityMst cityMst;
	private StateMst stateMst;
	private String firstName;
	private String lastName;
	private String fatherName;
	private String motherName;
	private Date dateOfBirth;
	private Character gender;
	private String emailId;
	private String mobileNo;
	private String password;
	private String addressLine1;
	private String addressLine2;
	private Long pinCode;
	private String district;
	private Character aadhaarCardApplicable;
	private String aadhaarCardNo;
	private Date createdDate;
	private Date modifiedDate;
	private Character profile;
	private Character isActive;
	private Set<TrainerDetails> trainerDetailses = new HashSet<TrainerDetails>(0);
	private Set<StudentDetails> studentDetailses = new HashSet<StudentDetails>(0);

	public PersonDetails() {
	}

	public PersonDetails(long personDetailsId) {
		this.personDetailsId = personDetailsId;
	}

	public PersonDetails(long personDetailsId, AcademicDetails academicDetails, CityMst cityMst, StateMst stateMst,
			String firstName, String lastName, String fatherName, String motherName, Date dateOfBirth, Character gender,
			String emailId, String mobileNo, String password, String addressLine1, String addressLine2, Long pinCode,
			String district, Character aadhaarCardApplicable, String aadhaarCardNo, Date createdDate, Date modifiedDate,
			Character profile, Character isActive, Set<TrainerDetails> trainerDetailses,
			Set<StudentDetails> studentDetailses) {
		this.personDetailsId = personDetailsId;
		this.academicDetails = academicDetails;
		this.cityMst = cityMst;
		this.stateMst = stateMst;
		this.firstName = firstName;
		this.lastName = lastName;
		this.fatherName = fatherName;
		this.motherName = motherName;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.emailId = emailId;
		this.mobileNo = mobileNo;
		this.password = password;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.pinCode = pinCode;
		this.district = district;
		this.aadhaarCardApplicable = aadhaarCardApplicable;
		this.aadhaarCardNo = aadhaarCardNo;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.profile = profile;
		this.isActive = isActive;
		this.trainerDetailses = trainerDetailses;
		this.studentDetailses = studentDetailses;
	}

	public long getPersonDetailsId() {
		return this.personDetailsId;
	}

	public void setPersonDetailsId(long personDetailsId) {
		this.personDetailsId = personDetailsId;
	}

	public AcademicDetails getAcademicDetails() {
		return this.academicDetails;
	}

	public void setAcademicDetails(AcademicDetails academicDetails) {
		this.academicDetails = academicDetails;
	}

	public CityMst getCityMst() {
		return this.cityMst;
	}

	public void setCityMst(CityMst cityMst) {
		this.cityMst = cityMst;
	}

	public StateMst getStateMst() {
		return this.stateMst;
	}

	public void setStateMst(StateMst stateMst) {
		this.stateMst = stateMst;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public Long getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(Long pinCode) {
		this.pinCode = pinCode;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public Character getAadhaarCardApplicable() {
		return this.aadhaarCardApplicable;
	}

	public void setAadhaarCardApplicable(Character aadhaarCardApplicable) {
		this.aadhaarCardApplicable = aadhaarCardApplicable;
	}

	public String getAadhaarCardNo() {
		return this.aadhaarCardNo;
	}

	public void setAadhaarCardNo(String aadhaarCardNo) {
		this.aadhaarCardNo = aadhaarCardNo;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Character getProfile() {
		return this.profile;
	}

	public void setProfile(Character profile) {
		this.profile = profile;
	}

	public Character getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}

	public Set<TrainerDetails> getTrainerDetailses() {
		return this.trainerDetailses;
	}

	public void setTrainerDetailses(Set<TrainerDetails> trainerDetailses) {
		this.trainerDetailses = trainerDetailses;
	}

	public Set<StudentDetails> getStudentDetailses() {
		return this.studentDetailses;
	}

	public void setStudentDetailses(Set<StudentDetails> studentDetailses) {
		this.studentDetailses = studentDetailses;
	}

}
