package in.coderinfotech.batchschedule;
// Generated Jan 20, 2018 8:05:27 PM by Hibernate Tools 5.2.6.Final

/**
 * TrainerDetails generated by hbm2java
 */
public class TrainerDetails implements java.io.Serializable {

	private long trainerDetailsId;
	private PersonDetails personDetails;
	private String trainerCode;
	private String title;
	private String areasOfSpecialization;
	private String department;
	private String officeLocation;
	private String officeTelephone;
	private String experience;
	private String researchInterests;
	private String projects;

	public TrainerDetails() {
	}

	public TrainerDetails(long trainerDetailsId) {
		this.trainerDetailsId = trainerDetailsId;
	}

	public TrainerDetails(long trainerDetailsId, PersonDetails personDetails, String trainerCode, String title,
			String areasOfSpecialization, String department, String officeLocation, String officeTelephone,
			String experience, String researchInterests, String projects) {
		this.trainerDetailsId = trainerDetailsId;
		this.personDetails = personDetails;
		this.trainerCode = trainerCode;
		this.title = title;
		this.areasOfSpecialization = areasOfSpecialization;
		this.department = department;
		this.officeLocation = officeLocation;
		this.officeTelephone = officeTelephone;
		this.experience = experience;
		this.researchInterests = researchInterests;
		this.projects = projects;
	}

	public long getTrainerDetailsId() {
		return this.trainerDetailsId;
	}

	public void setTrainerDetailsId(long trainerDetailsId) {
		this.trainerDetailsId = trainerDetailsId;
	}

	public PersonDetails getPersonDetails() {
		return this.personDetails;
	}

	public void setPersonDetails(PersonDetails personDetails) {
		this.personDetails = personDetails;
	}

	public String getTrainerCode() {
		return this.trainerCode;
	}

	public void setTrainerCode(String trainerCode) {
		this.trainerCode = trainerCode;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAreasOfSpecialization() {
		return this.areasOfSpecialization;
	}

	public void setAreasOfSpecialization(String areasOfSpecialization) {
		this.areasOfSpecialization = areasOfSpecialization;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getOfficeLocation() {
		return this.officeLocation;
	}

	public void setOfficeLocation(String officeLocation) {
		this.officeLocation = officeLocation;
	}

	public String getOfficeTelephone() {
		return this.officeTelephone;
	}

	public void setOfficeTelephone(String officeTelephone) {
		this.officeTelephone = officeTelephone;
	}

	public String getExperience() {
		return this.experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	public String getResearchInterests() {
		return this.researchInterests;
	}

	public void setResearchInterests(String researchInterests) {
		this.researchInterests = researchInterests;
	}

	public String getProjects() {
		return this.projects;
	}

	public void setProjects(String projects) {
		this.projects = projects;
	}

}
